# Generated by Django 5.1.7 on 2025-03-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ci",
            field=models.ForeignKey(
                blank=True,
                help_text="CI assigned to this student",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="centres.ci",
            ),
        ),
        migrations.AlterField(
            model_name="studentlevelhistory",
            name="completion_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="completion date"
            ),
        ),
    ]
