# Generated by Django 5.1.7 on 2025-04-19 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="User account associated with this student",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentlevelhistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who changed the level",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="level_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentlevelhistory",
            name="new_level",
            field=models.ForeignKey(
                help_text="New level of the student",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_students",
                to="students.level",
            ),
        ),
        migrations.AddField(
            model_name="studentlevelhistory",
            name="student",
            field=models.ForeignKey(
                help_text="Student whose level is being changed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="level_history",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["centre"], name="students_st_centre__8f1600_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentlevelhistory",
            index=models.Index(
                fields=["student", "created_at"], name="students_st_student_c54b2d_idx"
            ),
        ),
    ]
