# Generated by Django 5.1.7 on 2025-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
