# Generated by Django 5.1.7 on 2025-03-25 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_studentlevelhistory_changed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentlevelhistory",
            name="previous_level",
        ),
    ]
