# Generated by Django 5.1.7 on 2025-03-25 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0001_initial"),
        ("students", "0004_remove_studentlevelhistory_previous_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_is_acti_c00e81_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_centre__ba03cc_idx",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_active",
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["centre"], name="students_st_centre__8f1600_idx"
            ),
        ),
    ]
