steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_DOCKER_APP_NAME}'
      - '.'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_DOCKER_APP_NAME}']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_DOCKER_APP_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_DOCKER_APP_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--port'
      - '8080'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'