# Generated by Django 5.1.7 on 2025-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsection",
            name="title",
        ),
        migrations.AddField(
            model_name="testsection",
            name="section_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="Section Type"),
        ),
    ]
