# Generated by Django 5.1.7 on 2025-05-01 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTestAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("total_questions", models.IntegerField()),
                ("total_attempted", models.IntegerField()),
                ("total_marks", models.FloatField()),
                ("marks_obtained", models.FloatField()),
                ("correct_answers", models.IntegerField()),
                ("incorrect_answers", models.IntegerField()),
                ("accuracy_percentage", models.FloatField()),
                ("answers_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests_app.studenttest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
