# Generated by Django 5.1.7 on 2025-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0002_studenttestanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttestanalytics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="studenttestanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
    ]
