# Generated by Django 5.1.7 on 2025-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0002_remove_testsection_title_testsection_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Due date"
            ),
        ),
        migrations.AlterField(
            model_name="testsection",
            name="section_type",
            field=models.CharField(max_length=100, verbose_name="Section Type"),
        ),
    ]
