# Generated by Django 5.1.7 on 2025-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_remove_level_is_approved_student_is_approved"),
        ("tests_app", "0003_studenttestanalytics_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studenttestanalytics",
            options={"verbose_name": "StudentTest Analytics"},
        ),
        migrations.AddIndex(
            model_name="studenttest",
            index=models.Index(
                fields=["end_time"], name="tests_app_s_end_tim_e10c88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studenttestanalytics",
            index=models.Index(
                fields=["marks_obtained"], name="tests_app_s_marks_o_d6571e_idx"
            ),
        ),
    ]
