# Generated by Django 5.1.7 on 2025-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0003_test_due_date_alter_testsection_section_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="tests_app_q_section_e25a9f_idx",
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("plus", "Plus/Addition"),
                    ("minus", "Minus/Subtraction"),
                    ("multiple", "Multiple Choice"),
                    ("divide", "Divide/Division"),
                    ("short_answer", "Short Answer"),
                    ("true_false", "True/False"),
                    ("matching", "Matching"),
                    ("fill_blank", "Fill in the Blank"),
                ],
                default="multiple",
                max_length=20,
                verbose_name="question type",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["section", "question_type", "order"],
                name="tests_app_q_section_f2242d_idx",
            ),
        ),
    ]
