# Generated by Django 5.1.7 on 2025-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0004_remove_question_tests_app_q_section_e25a9f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("plus", "Plus/Addition"),
                    ("multiple", "Multiple Choice"),
                    ("divide", "Divide/Division"),
                ],
                default="multiple",
                max_length=20,
                verbose_name="question type",
            ),
        ),
    ]
