# Generated by Django 5.1.7 on 2025-03-27 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0006_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together=set(),
        ),
    ]
