# Generated by Django 5.1.7 on 2025-03-27 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0007_alter_studentanswer_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together={("student_test", "question")},
        ),
    ]
