# Generated by Django 5.1.7 on 2025-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests_app", "0008_alter_studentanswer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("plus", "Plus/Addition"),
                    ("multiply", "Multiply"),
                    ("divide", "Divide/Division"),
                ],
                default="plus",
                max_length=20,
                verbose_name="question type",
            ),
        ),
    ]
